"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from os import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#### NGINX Config paths

NGINX_CONFIG_DIR = "/etc/nginx/conf.d"
NGINX_CONFIG_FILE = "valid_cookies.conf"

VCENTER_DOMAIN= str(environ.get('VCENTER_DOMAIN','vcenter.aqr.net'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b5#-chd28v*!1x(efuvw0zo0f(wmyr%lt2%&2ap@7_e$%^_qs9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(environ.get('DJANGO_DEBUG','1')))

ALLOWED_HOSTS = ['localhost','0.0.0.0','127.0.0.1']
ALLOWED_HOSTS.append(VCENTER_DOMAIN)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrapform',
    'accounts',
    'pwm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'accounts.middleware.UserActivityLoggerMiddleware',    # If enable this middleware all user activities log in database
]

ROOT_URLCONF = 'core.urls'
# settings.py

# SESSION_COOKIE_NAME = 'my_session_id'  # Customize your session cookie name
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': environ.get("DB_DATABASE","aidmdb"),
        'USER': environ.get("DB_USER","aidmuser"),
        'PASSWORD': environ.get("DB_PASSWORD","dfrgfdtgtrghtr"),
        'HOST': environ.get("DB_CONTAINER_NAME","192.168.240.2") ,   # Or an IP Address that your DB is hosted on
        'PORT': environ.get("DB_PORT","3306") ,
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
    BASE_DIR / "static_files",
    
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# user manager config
AUTH_USER_MODEL = "accounts.User"


LOGIN_URL = "pwm:login"
LOGIN_REDIRECT_URL = "pwm:dashboard"
LOGOUT_REDIRECT_URL = LOGIN_URL

